apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  dockerwithmongo2-Dp
  labels:
    name: node&Mongo
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  dockerwithmongo2-POD
    spec:
      containers:
      - image:  pralhadkharel/dockerwithmongo2
        name:  dockerwithmongo2-Co
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        
        env:
        - name:  ENVVARNAME
          value:  ENVVARVALUE       
        ports:
        - containerPort:  4444
          name:  my-name
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          emptyDir: {}
      restartPolicy: Always
      imagePullPolicy: Always